"""
app/models/base.py

Shared SQLAlchemy mixins that every ORM model in Technify VisionAI reuses.

Every table gets:
- `id`         : a UUID primary key generated by Postgres itself
                 (gen_random_uuid()), so rows inserted DIRECTLY via Supabase
                 or the edge service also get IDs — not only rows created
                 through SQLAlchemy.
- `created_at` : set once, by the database, on insert.
- `updated_at` : set on insert and bumped by SQLAlchemy on update.

Models combine these mixins with the declarative `Base` defined in
app/core/database.py:

    from app.core.database import Base
    from app.models.base import UUIDMixin, TimestampMixin

    class Organization(UUIDMixin, TimestampMixin, Base):
        __tablename__ = "organizations"
        name: Mapped[str] = mapped_column(String(255), nullable=False)

Mixin order matters for column layout only (id/timestamps first); it has no
effect on behavior. Keep `Base` LAST in the inheritance list.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDMixin:
    """Adds a UUID primary key that Postgres generates by default."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        # Postgres generates the ID. gen_random_uuid() is built in on
        # Supabase, so direct SQL / Supabase-client inserts get an ID too.
        server_default=text("gen_random_uuid()"),
        # Client-side fallback so ORM-created objects have an .id immediately,
        # before the row is flushed to the database.
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Adds created_at / updated_at audit columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        # Fires on UPDATEs issued through SQLAlchemy. (Direct Supabase updates
        # won't trigger this — we can add a DB trigger later if we ever need
        # updated_at to be authoritative for non-ORM writes.)
        onupdate=func.now(),
    )